baseurl                 = "achtung.es/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Alvaro Navarro website"
theme                   = "sam"
publishDir              = "docs"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = ""

# Metadata
    description         = "Alvaro Navarro website"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "https://github.com/alnacle"
    text = "code"

[[params.mainMenu]]
    link = "http://flickr.com/18r"
    text = "gallery"

[[params.mainMenu]]
    link = "https://twitter.com/alnacle"
    text = "twitter"

[[params.mainMenu]]
    link = "/about"
    text = "about"
    
